export const projects = [
  {
    id: "1",
    slug: "proyecto-alpha",
    title: "Proyecto Alpha",
    description: "Una aplicación web de vanguardia desarrollada con Next.js y TypeScript, que muestra una arquitectura de frontend moderna y una experiencia de usuario fluida.",
    longDescription: "Proyecto Alpha es una plataforma integral diseñada para optimizar los flujos de trabajo de desarrollo. Desde la planificación hasta el despliegue, esta herramienta ofrece una solución unificada con un enfoque en la colaboración en tiempo real y la automatización. La interfaz, construida con Tailwind CSS, es completamente responsiva y personalizable.",
    coverImageId: "project-1",
    galleryImageIds: ["project-1", "project-2", "project-3"],
    link: "#",
    tags: ["Next.js", "TypeScript", "Tailwind CSS", "Vercel"],
  },
  {
    id: "2",
    slug: "proyecto-beta",
    title: "Proyecto Beta",
    description: "Este proyecto explora funciones sin servidor y la infraestructura en la nube, proporcionando una solución de backend robusta para aplicaciones de alto tráfico.",
    longDescription: "Proyecto Beta aprovecha el poder de las arquitecturas sin servidor para ofrecer una escalabilidad y rentabilidad incomparables. Utilizando Firebase para la autenticación y la base de datos en tiempo real, y Node.js para la lógica de backend, esta aplicación puede manejar miles de solicitudes por segundo sin problemas. Es ideal para startups y empresas que buscan un crecimiento rápido.",
    coverImageId: "project-2",
    galleryImageIds: ["project-2", "project-3", "project-1"],
    link: "#",
    tags: ["Serverless", "Firebase", "Node.js", "Google Cloud"],
  },
  {
    id: "3",
    slug: "proyecto-gamma",
    title: "Proyecto Gamma",
    description: "Una librería de visualización de datos de código abierto construida con D3.js, que ofrece gráficos interactivos y personalizables para conjuntos de datos complejos.",
    longDescription: "Proyecto Gamma nació de la necesidad de visualizar datos complejos de una manera intuitiva y estéticamente agradable. Esta librería de JavaScript de código abierto permite a los desarrolladores crear gráficos de barras, de líneas, de dispersión y mapas de calor totalmente personalizables e interactivos. Es una herramienta poderosa para el análisis de datos y la narración de historias.",
    coverImageId: "project-3",
    galleryImageIds: ["project-3", "project-1", "project-2"],
    link: "#",
    tags: ["D3.js", "Data Viz", "Open Source", "JavaScript"],
  },
];
