export const daeliaSections = [
  {
    id: "d",
    letter: "D",
    title: "ISRUPCION",
    description: "Rompiendo paradigmas establecidos. Si no es diferente, no es Daelia.",
    bgColor: "bg-blue-950",
    textColor: "text-blue-300",
    scrollbarColor: "hsl(224, 71%, 10%)",
    scrollbarHoverColor: "hsl(224, 71%, 20%)",
  },
  {
    id: "a",
    letter: "A",
    title: "RTE",
    description: "Donde la logica se encuentra con la estetica. Cada pixel cuenta una historia.",
    bgColor: "bg-blue-900",
    textColor: "text-blue-400",
    scrollbarColor: "hsl(224, 71%, 15%)",
    scrollbarHoverColor: "hsl(224, 71%, 25%)",
  },
  {
    id: "e",
    letter: "E",
    title: "XPLORACION",
    description: "Navegando nuevas fronteras tecnologicas. El mapa no es el territorio.",
    bgColor: "bg-blue-800",
    textColor: "text-blue-300",
    scrollbarColor: "hsl(224, 71%, 20%)",
    scrollbarHoverColor: "hsl(224, 71%, 30%)",
  },
  {
    id: "l",
    letter: "L",
    title: "ABORATORIO",
    description: "Espacio para la innovacion constante. Fallar rapido, aprender mas rapido.",
    bgColor: "bg-blue-700",
    textColor: "text-blue-200",
    scrollbarColor: "hsl(224, 71%, 30%)",
    scrollbarHoverColor: "hsl(224, 71%, 40%)",
  },
  {
    id: "i",
    letter: "I",
    title: "MAGINACION",
    description: "Visualizando lo imposible. Lo que puedes sonar, lo puedes codificar.",
    bgColor: "bg-blue-600",
    textColor: "text-blue-100",
    scrollbarColor: "hsl(224, 71%, 40%)",
    scrollbarHoverColor: "hsl(224, 71%, 50%)",
  },
  {
    id: "a2",
    letter: "A",
    title: "UDACIA",
    description: "Atrevete a crear diferente. El conformismo es el enemigo de la evolucion.",
    bgColor: "bg-blue-500",
    textColor: "text-blue-950",
    scrollbarColor: "hsl(224, 71%, 50%)",
    scrollbarHoverColor: "hsl(224, 71%, 60%)",
  },
];
