export const overrideSections = [
  {
    id: "o",
    letter: "O",
    title: "RIGEN",
    description: "El punto de partida para la transformacion digital. Construimos desde cero con bases solidas.",
    bgColor: "bg-black",
    textColor: "text-neutral-300",
    scrollbarColor: "hsl(0, 0%, 0%)",
    scrollbarHoverColor: "hsl(0, 0%, 20%)",
  },
  {
    id: "v",
    letter: "V",
    title: "ISION",
    description: "Anticipamos el futuro con soluciones escalables que crecen junto a tu negocio.",
    bgColor: "bg-neutral-900",
    textColor: "text-neutral-400",
    scrollbarColor: "hsl(0, 0%, 10%)",
    scrollbarHoverColor: "hsl(0, 0%, 30%)",
  },
  {
    id: "e",
    letter: "E",
    title: "FICACIA",
    description: "Resultados medibles y optimizacion de recursos. Hacemos mas con menos.",
    bgColor: "bg-neutral-800",
    textColor: "text-neutral-500",
    scrollbarColor: "hsl(0, 0%, 20%)",
    scrollbarHoverColor: "hsl(0, 0%, 40%)",
  },
  {
    id: "r",
    letter: "R",
    title: "IGOR",
    description: "Codigo robusto y arquitecturas solidas. Calidad innegociable en cada linea.",
    bgColor: "bg-neutral-700",
    textColor: "text-neutral-300",
    scrollbarColor: "hsl(0, 0%, 30%)",
    scrollbarHoverColor: "hsl(0, 0%, 50%)",
  },
  {
    id: "r2",
    letter: "R",
    title: "APIDEZ",
    description: "Despliegues agiles y rendimiento superior. Tu tiempo es el recurso mas valioso.",
    bgColor: "bg-neutral-600",
    textColor: "text-neutral-200",
    scrollbarColor: "hsl(0, 0%, 40%)",
    scrollbarHoverColor: "hsl(0, 0%, 60%)",
  },
  {
    id: "i",
    letter: "I",
    title: "NGENIO",
    description: "Soluciones creativas a problemas complejos. Pensamos fuera de la caja.",
    bgColor: "bg-neutral-500",
    textColor: "text-neutral-800",
    scrollbarColor: "hsl(0, 0%, 50%)",
    scrollbarHoverColor: "hsl(0, 0%, 70%)",
  },
  {
    id: "d",
    letter: "D",
    title: "OMINIO",
    description: "Control total sobre tu infraestructura tecnologica. Seguridad y estabilidad garantizadas.",
    bgColor: "bg-neutral-400",
    textColor: "text-neutral-900",
    scrollbarColor: "hsl(0, 0%, 60%)",
    scrollbarHoverColor: "hsl(0, 0%, 80%)",
  },
  {
    id: "e2",
    letter: "E",
    title: "COSISTEMA",
    description: "Integracion perfecta de todas tus herramientas. Un todo cohesivo y funcional.",
    bgColor: "bg-neutral-300",
    textColor: "text-black",
    scrollbarColor: "hsl(0, 0%, 70%)",
    scrollbarHoverColor: "hsl(0, 0%, 90%)",
  },
];
