export const parseSections = [
  {
    id: "features",
    letter: "F",
    title: "EATURES",
    description: "Experiencia de lectura inmersiva estilo Kindle. Gestion de biblioteca, soporte PDF y mas.",
    bgColor: "bg-purple-200",
    textColor: "text-purple-900",
    scrollbarColor: "hsl(270, 50%, 70%)",
    scrollbarHoverColor: "hsl(270, 50%, 60%)",
  },
  {
    id: "tech",
    letter: "S",
    title: "TACK",
    description: "Kotlin, Jetpack Compose, Koin, Ktor, Room, Coil 3. Tecnologia de punta para Android.",
    bgColor: "bg-purple-300",
    textColor: "text-purple-950",
    scrollbarColor: "hsl(270, 50%, 60%)",
    scrollbarHoverColor: "hsl(270, 50%, 50%)",
  },
  {
    id: "structure",
    letter: "M",
    title: "ODULAR",
    description: "Clean Architecture modular. Separacion clara por features: auth, home, book, settings.",
    bgColor: "bg-purple-400",
    textColor: "text-purple-950",
    scrollbarColor: "hsl(270, 50%, 50%)",
    scrollbarHoverColor: "hsl(270, 50%, 40%)",
  },
  {
    id: "start",
    letter: "G",
    title: "ET IT",
    description: "Clona el repo, configura Firebase y compila. Open source y listo para contribuir.",
    bgColor: "bg-purple-500",
    textColor: "text-white",
    scrollbarColor: "hsl(270, 50%, 40%)",
    scrollbarHoverColor: "hsl(270, 50%, 30%)",
  },
];
